/**
 * KELİMEBAZ — TEMA SETLERİ üretici (TR + EN).
 *
 * Her tema için ELLE KÜRATÖRLÜ tanıdık kelime adayları verilir; betik bunları
 * OYUN SÖZLÜĞÜNE (valid-words) ve 4-7 harf kuralına göre SÜZER, benzersizleştirir,
 * uzunluk dağılımını raporlar ve her temada ≥40 kelime olduğunu doğrular.
 *
 * NEDEN elle küratör: temalı gruplama ANLAMSAL bir iştir; frekans/heuristik
 * yapamaz. Adaylar tanıdık seçilir → tema setlerine yabancı kelime girmez
 * (OYUN-193 bağımlılığının amacı). ANTHROPIC_API_KEY verilirse ileride aynı
 * betik LLM ile adayları GENİŞLETİP kaliteyi artırabilir (şimdilik küratör v1).
 *
 * Çıktı: src/app/data/themes-tr.json ve -en.json
 *   { "version": 1, "themes": { "kitchen": ["KELİME", ...], ... } }
 *
 * Kullanım: npm run build:themes
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const DATA = new URL('../src/app/data/', import.meta.url);
const MIN_PER_THEME = 40;

/** 8 tema — id sırası UI ile aynı. İkon/renk UI'da (theme-screen) tanımlı. */
export const THEME_IDS = [
  'kitchen',
  'nature',
  'sport',
  'music',
  'health',
  'transport',
  'emotions',
  'history',
];

// ── ELLE KÜRATÖRLÜ ADAYLAR (BÜYÜK harf; betik sözlükte olmayan/kısa olanı eler) ──

const TR = {
  kitchen: `TAVA TENCERE KAŞIK ÇATAL TABAK BARDAK FIRIN OCAK BIÇAK KEPÇE TUZLUK SÜZGEÇ RENDE HAVAN TEPSİ KAVANOZ IZGARA SOFRA EKMEK PEYNİR ZEYTİN YOĞURT SALATA ÇORBA PİLAV KÖFTE BÖREK TATLI ŞEKER YUMURTA DOMATES BİBER SOĞAN PATATES HAVUÇ LİMON ELMA ARMUT KİRAZ KAYISI KARPUZ KAVUN ÜZÜM İNCİR ÇİLEK REÇEL KAHVE AYRAN MENÜ GARSON MUTFAK YEMEK KAZAN DOLAP BULAŞIK PEÇETE UNLU HAMUR MAYA TUZLU`,
  nature: `ORMAN DENİZ NEHİR AĞAÇ ÇİÇEK YAPRAK TOPRAK BULUT YAĞMUR RÜZGAR GÜNEŞ YILDIZ DALGA KAYA VADİ ÇİMEN MANTAR BÖCEK KELEBEK BALIK GEYİK TİLKİ KURT TAVŞAN ASLAN KAPLAN MAYMUN KARTAL SERÇE BAYKUŞ YILAN ARI KARINCA ÖRÜMCEK PALMİYE MEŞE ÇINAR KAVAK GÜL LALE PAPATYA MENEKŞE SÜMBÜL YOSUN ÇALI DİKEN KOZALAK TOHUM FİDAN DOĞA IRMAK ŞELALE MAĞARA TEPE OVASI KUMSAL ADALAR ÇAKIL`,
  sport: `FUTBOL BASKET VOLEYBOL TENİS GÜREŞ BOKS YÜZME KOŞU ATLET STADYUM SAHA TAKIM OYUNCU HAKEM KALE TOPU PENALTI KORNER SKOR GALİBİYET MADALYA KUPA ŞAMPİYON FORMA RAKET FİLE POTA SEPET YOKUŞ KAYAK PATEN OKÇULUK ESKRİM HALTER JİMNASTİK RUGBİ HENTBOL SUTOPU MARATON REKOR ANTRENÖR KONDİSYON DEPLASMAN TARAFTAR TRİBÜN DÜDÜK SAYI SET DEVRE`,
  music: `MÜZİK ŞARKI NOTA MELODİ RİTİM GİTAR PİYANO KEMAN FLÜT DAVUL TRAMPET ZURNA SAZ BAĞLAMA UD KANUN NEY TAMBUR ÇELLO ARP AKORT KORO SOLO ORKESTRA KONSER SAHNE DİNLETİ ALBÜM NAKARAT GÜFTE BESTE ŞARKICI MÜZİSYEN ORG SENTEZ TON PERDE OKTAV ENSTRUMAN MİKROFON HOPARLÖR KLARNET OBUA TROMBON SAKSOFON TÜRKÜ MARŞ İLAHİ EZGİ MAKAM GAZEL USÜL TINI MIZRAP TELLİ ÜFLEME VURMALI BANDO DÜET TRİO MİNÖR MAJÖR PORTE ANAHTAR STÜDYO PLAK KASET RADYO KAVAL DİNLE SÖZLER MARŞLAR RİTİMLİ NAĞME`,
  health: `SAĞLIK DOKTOR HEMŞİRE HASTANE İLAÇ AŞI İĞNE REÇETE TANSİYON ATEŞ GRİP NEZLE ÖKSÜRÜK AĞRI YARA BANDAJ ALÇI RÖNTGEN AMELİYAT KALP CİĞER BEYİN BÖBREK MİDE KEMİK KAS DAMAR KAN NABIZ VİTAMİN DİYET EGZERSİZ UYKU DİNLENME MUAYENE POLİKLİNİK ECZANE SERUM MASKE VİRÜS MİKROP BAĞIŞIK TERMOMETRE STETOSKOP GARGARA MERHEM ŞURUP HAP TEDAVİ TEŞHİS HASTA SARGI PAMUK ALKOL KIRIK ÇIKIK TAHLİL İDRAR KAPSÜL DAMLA KREM LOSYON GÖZLÜK ORGAN DOKU HÜCRE PERHİZ KALORİ PROTEİN SOLUNUM NEFES TİTREME NEKAHAT SANCI ÜŞÜME`,
  transport: `ARABA OTOBÜS KAMYON MİNİBÜS TREN METRO TRAMVAY VAPUR GEMİ TEKNE UÇAK HELİKOPTER BİSİKLET MOTOR SCOOTER TAKSİ YOLCU ŞOFÖR KAPTAN PİLOT BİLET DURAK İSTASYON LİMAN HAVAALANI GARAJ TÜNEL KÖPRÜ YOL OTOBAN VİRAJ KAVŞAK TRAFİK SİNYAL FREN DİREKSİYON LASTİK MOTORU KOLTUK BAGAJ ROTA SEFER PERON RAYLAR VAGON DÜMEN YELKEN KÜREK`,
  emotions: `MUTLU ÜZGÜN KIZGIN KORKU SEVİNÇ HÜZÜN ÖFKE NEŞE HEYECAN KAYGI ENDİŞE UMUT ÖZLEM PİŞMAN GURUR UTANÇ KISKANÇ SEVGİ NEFRET MERAK ŞAŞKIN YORGUN HUZUR KEDER ACIMA CESARET İNAT NAZ ŞEFKAT MERHAMET VİCDAN DUYGU HİSSET SAKİN GERGİN COŞKU KEYİF SIKINTI BUNALIM FERAH MEMNUN MİNNET HAYRET DEHŞET`,
  history: `TARİH KRAL KRALİÇE SULTAN PADİŞAH İMPARATOR SARAY TAHT TAÇ KALE SUR KILIÇ KALKAN ZIRH MIZRAK OK YAY SAVAŞ ORDU ASKER KOMUTAN ZAFER FETİH ANTLAŞMA İSYAN DEVRİM HANEDAN VEZİR PAŞA BEYLİK OSMANLI SELÇUKLU MÜZE ANIT MEZAR PİRAMİT TAPINAK HEYKEL YAZIT FERMAN ARŞİV ÇAĞLAR DÖNEM UYGARLIK MEDENİYET GÖÇEBE KAĞAN ELÇİ KUŞATMA İSTİLA SÜRGÜN ANTİK DEVİR ASIR YÜZYIL KABİLE AŞİRET HAZİNE GANİMET ESİR KÖLE EFENDİ TIMAR AKINCI TOPÇU MEŞALE KİTABE LAHİT MUMYA FİRAVUN ÇAĞDAŞ`,
};

const EN = {
  kitchen: `SPOON PLATE KNIFE FORK STOVE OVEN GRILL KETTLE BOWL GLASS BREAD CHEESE BUTTER SUGAR COFFEE SALAD SOUP DINNER RECIPE KITCHEN PANTRY APRON WHISK LADLE GRATER TEAPOT SAUCER NAPKIN TOASTER BLENDER PASTA PIZZA SAUCE FLOUR HONEY LEMON APPLE GRAPE PEACH ONION GARLIC POTATO CARROT TOMATO PEPPER PICKLE ROAST STEAK CREAM PLATTER`,
  nature: `FOREST RIVER OCEAN BEACH VALLEY MEADOW MOUNTAIN DESERT ISLAND JUNGLE FLOWER LEAF ROOT SEED BRANCH BREEZE STORM CLOUD RAIN THUNDER SUNSET RAINBOW PEBBLE BOULDER STREAM MEADOW FOSSIL CANYON PRAIRIE TIGER LION MONKEY EAGLE SPARROW RABBIT SNAKE SPIDER BEETLE INSECT SALMON WHALE DOLPHIN CACTUS MAPLE WILLOW DAISY VIOLET TULIP MOSS FERN`,
  sport: `SOCCER TENNIS BOXING RUNNING SWIM SKATE SKIING HOCKEY RUGBY CRICKET GOLF ARCHERY FENCING ROWING SPRINT MARATHON REFEREE PLAYER STADIUM ARENA TROPHY MEDAL CHAMPION SCORE GOAL RACKET HELMET JERSEY WHISTLE COACH DEFENSE OFFENSE PENALTY CORNER PITCH COURT TRACK FIELD BOWLING SURFING DIVING CYCLING SKATING BATTER PITCHER TACKLE`,
  music: `MUSIC SONG NOTE MELODY RHYTHM GUITAR PIANO VIOLIN FLUTE DRUM TRUMPET CELLO HARP BANJO ORGAN CHORD CHOIR TEMPO CONCERT STAGE ALBUM SINGER LYRIC OPERA JAZZ BLUES CLASSIC ANTHEM ENCORE OCTAVE TUNE BEAT BASS TREBLE OBOE CLARINET TROMBONE CORNET UKULELE FIDDLE CYMBAL RECORD STEREO SPEAKER RECITAL BALLAD`,
  health: `HEALTH DOCTOR NURSE CLINIC MEDICINE VACCINE NEEDLE PILL SYRUP BANDAGE PLASTER FEVER COUGH ALLERGY WOUND SCAR MUSCLE BONE HEART LIVER KIDNEY BRAIN NERVE BLOOD PULSE VITAMIN DIET EXERCISE SLEEP CHECKUP SURGERY PATIENT DENTIST HOSPITAL PHARMACY THERAPY MASK VIRUS GERM IMMUNE STRETCHER OINTMENT LOTION TABLET REMEDY HEALTHY ILLNESS INJURY RASH SPRAIN GAUZE SPLINT ARTERY LUNGS STOMACH GLAND SYRINGE DOSAGE WARD CAPSULE SCAN ACHE SWAB TISSUE RECOVER OXYGEN HYGIENE DENTAL CRUTCH PLAGUE`,
  transport: `CAR BUS TRUCK TRAIN METRO TRAM FERRY SHIP BOAT PLANE JET SCOOTER MOTOR TAXI CABIN DRIVER PILOT CAPTAIN SAILOR TICKET STATION AIRPORT HARBOR GARAGE TUNNEL BRIDGE HIGHWAY TRAFFIC SIGNAL BRAKE WHEEL ENGINE SEAT LUGGAGE ROUTE VOYAGE PLATFORM WAGON RUDDER PADDLE ANCHOR SUBWAY CANOE YACHT ROCKET SLEDGE TROLLEY`,
  emotions: `HAPPY SAD ANGRY FEAR JOY SORROW RAGE CHEER EXCITED ANXIOUS WORRY HOPE LONGING REGRET PRIDE SHAME JEALOUS LOVE HATRED CURIOUS SURPRISE TIRED CALM GRIEF PITY COURAGE ENVY TENDER MERCY GUILT EMOTION FEELING NERVOUS THRILL DELIGHT BOREDOM GLOOM RELIEF CONTENT GRATEFUL WONDER DREAD PANIC LONELY EAGER`,
  history: `HISTORY KING QUEEN SULTAN EMPEROR PALACE THRONE CROWN CASTLE FORT SWORD SHIELD ARMOR SPEAR ARROW BATTLE ARMY SOLDIER GENERAL VICTORY CONQUEST TREATY REVOLT REVOLUTION DYNASTY EMPIRE KINGDOM KNIGHT MUSEUM MONUMENT TOMB PYRAMID TEMPLE STATUE ANCIENT MEDIEVAL LEGEND RELIC ARCHIVE ERA CENTURY NOMAD RUINS SIEGE PHARAOH SCROLL`,
};

const chars = (w) => [...w];
const ok47 = (w) => chars(w).length >= 4 && chars(w).length <= 7;

async function buildLang(lang, curated) {
  const file = lang === 'tr' ? 'valid-words.json' : 'valid-words-en.json';
  const valid = new Set(
    JSON.parse(await readFile(new URL(file, DATA), 'utf8'))
      .words.split(' ')
      .filter(Boolean),
  );

  const themes = {};
  let problems = 0;
  console.log(`\n[${lang}]`);
  for (const id of THEME_IDS) {
    const raw = [...new Set(curated[id].trim().split(/\s+/))];
    const kept = raw.filter((w) => ok47(w) && valid.has(w));
    const dropped = raw.filter((w) => !(ok47(w) && valid.has(w)));
    themes[id] = kept;

    const dist = { 4: 0, 5: 0, 6: 0, 7: 0 };
    for (const w of kept) dist[chars(w).length]++;
    const mark = kept.length >= MIN_PER_THEME ? '✓' : '✗';
    console.log(
      `  ${mark} ${id.padEnd(10)} ${kept.length} kelime · uzunluk ${JSON.stringify(dist)}`,
    );
    if (dropped.length) console.log(`      elenen: ${dropped.join(' ')}`);
    if (kept.length < MIN_PER_THEME) problems++;
  }

  await writeFile(
    fileURLToPath(new URL(`themes-${lang}.json`, DATA)),
    JSON.stringify({ version: 1, themes }) + '\n',
  );
  return problems;
}

let problems = 0;
problems += await buildLang('tr', TR);
problems += await buildLang('en', EN);

if (problems) {
  console.error(`\n❌ ${problems} tema 40 kelimenin altında — aday listesini genişlet.`);
  process.exit(1);
}
console.log('\n✅ Tema setleri yazıldı (themes-tr/en.json), her tema ≥40 kelime.');
